### ISSUE TITLE
The stats page should be on /stats and not /ipfs/stats

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/service-worker-gateway-2019-poc#18]
`/ipfs/stats - Get the current stats of the IPFS Node running in the service worker` is polluting the `/ipfs` namespace.

**Comment by vasco-santos** [comment]
This should be correct since v0.1.3, and more precisely this PR #17 . Did you find any problem?

**Comment by daviddias** [comment]
See:

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/1211152/42445508-a6553d2c-8373-11e8-8362-99a156831e06.png">

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/1211152/42445515-ab01fa36-8373-11e8-9350-d05360200b1b.png">

**Comment by vasco-santos** [comment]
Hey David, 

Those pictures seem like the service worker was not running, since the service worker did not fetch the request before arriving to gatsby. Anyway, the project being tested `js.ipfs.io` has a package-lock, which was locking the `service-worker-gateway` version. I made a [PR](https://github.com/ipfs/js.ipfs.io/pull/25) for updating its version and tested locally with `localhost:8000/stats` and the stats page showed up correclty.

**Comment by daviddias** [comment]
Thank you @vasco-santos!
